#!/usr/bin/env python3
"""Report SMBEngine's methods by length, longest first, to METHOD_LENGTHS.md.

Run from the repo root:  python3 tools/method_lengths.py [outfile]

The short methods are candidates for inlining, the long ones for breaking up.
Comments and string literals are masked out before any brace matching or line
counting, so apostrophes in prose ("enemy's") do not derail the scan.
"""
import re, glob, os, json, sys, collections

def mask(src):
    out = list(src); i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c == '/' and i+1 < n and src[i+1] == '/':
            while i < n and src[i] != '\n': out[i] = ' '; i += 1
        elif c == '/' and i+1 < n and src[i+1] == '*':
            out[i] = out[i+1] = ' '; i += 2
            while i < n and not (src[i] == '*' and i+1 < n and src[i+1] == '/'):
                if src[i] != '\n': out[i] = ' '
                i += 1
            if i < n: out[i] = out[i+1] = ' '; i += 2
        elif c in '"\'':
            q = c; out[i] = ' '; i += 1
            while i < n and src[i] != q:
                if src[i] == '\\': out[i] = ' '; i += 1
                if i < n:
                    if src[i] != '\n': out[i] = ' '
                    i += 1
            if i < n: out[i] = ' '; i += 1
        else: i += 1
    return ''.join(out)

pat = re.compile(r'\bSMBEngine::(\w+)\s*\(')
rows, masked = [], {}
for path in sorted(glob.glob('source/SMB/*.cpp')):
    raw = open(path).read()
    src = mask(raw); masked[path] = src
    mlines, rlines = src.split('\n'), raw.split('\n')
    for m in pat.finditer(src):
        name = m.group(1)
        i = src.index('(', m.start())
        depth, j = 0, i
        while j < len(src):
            if src[j] == '(': depth += 1
            elif src[j] == ')':
                depth -= 1
                if depth == 0: break
            j += 1
        k = j + 1
        while k < len(src) and src[k] not in '{;': k += 1
        if k >= len(src) or src[k] == ';': continue
        depth, e = 0, k
        while e < len(src):
            if src[e] == '{': depth += 1
            elif src[e] == '}':
                depth -= 1
                if depth == 0: break
            e += 1
        s_ln, e_ln = src.count('\n', 0, m.start()), src.count('\n', 0, e)
        # body = code lines strictly inside the outermost braces
        b_ln, be_ln = src.count('\n', 0, k), e_ln
        body = [l for l in mlines[b_ln:be_ln+1] if l.strip() not in ('', '{', '}')]
        # data tables declared inside the body are bulk, not logic
        data = sum(1 for l in mlines[b_ln:be_ln+1] if l.strip() and not l.strip() in ('{','}'))
        rows.append({
            'name': name, 'file': os.path.basename(path), 'line': s_ln+1,
            'total': e_ln-s_ln+1,
            'code': sum(1 for l in mlines[s_ln:e_ln+1] if l.strip()),
            'body': len(body),
            'src': '\n'.join(rlines[s_ln:e_ln+1]),
        })

# Count call sites across the whole source tree, not just source/SMB -- the public
# API of SMBEngine is called from main.cpp and friends, and would otherwise look dead.
scan = dict(masked)
# .cpp only: a header's declaration would otherwise read as a call.
for extra in glob.glob('source/**/*.cpp', recursive=True):
    if extra not in scan:
        scan[extra] = mask(open(extra, errors='replace').read())
alltext = '\n'.join(scan.values())
defs = {r['name'] for r in rows}
calls = collections.Counter()
for m in re.finditer(r'\b(\w+)\s*\(', alltext):
    if m.group(1) in defs or m.group(1) in ('M', 'W'): calls[m.group(1)] += 1
qual = collections.Counter(re.findall(r'\bSMBEngine::(\w+)\s*\(', alltext))
# SMB.hpp reaches these two through macros, so the bare name never appears
MACRO_ALIAS = {'getMemory': 'M', 'getMemoryWord': 'W'}
for r in rows:
    n = r['name']
    r['calls'] = calls[n] - qual[n]                   # drop the definition itself
    if n in MACRO_ALIAS:
        r['calls'] += calls[MACRO_ALIAS[n]]
        r['via'] = MACRO_ALIAS[n] + '()'

rows.sort(key=lambda r: (-r['body'], r['name']))

out = []
w = out.append

total_body = sum(r['body'] for r in rows if r['name'] != 'loadConstantData')
w("# SMBEngine methods by length\n")
w("Generated by `tools/method_lengths.py` (re-run it to refresh).\n")
w("`body` is code lines strictly inside the outermost braces, with comments and")
w("blank lines removed -- so a one-statement method is `body 1`, not 4. `calls`")
w("counts call sites across all of `source/SMB/*.cpp`, excluding the definition;")
w("`0 calls` means nothing in the port reaches it.\n")
w(f"{len(rows)} methods, {total_body} body lines (excluding the generated")
w("`loadConstantData`).\n")

w("## Distribution\n")
buckets = [('0-1  (one-liners)', 0, 1), ('2-3', 2, 3), ('4-10', 4, 10),
           ('11-25', 11, 25), ('26-60', 26, 60), ('61-150', 61, 150), ('150+', 151, 10**9)]
w("| body lines | methods |")
w("|---|---:|")
for label, lo, hi in buckets:
    w(f"| {label} | {sum(1 for r in rows if lo <= r['body'] <= hi)} |")
w("")

by_file = collections.Counter()
body_by_file = collections.Counter()
for r in rows:
    by_file[r['file']] += 1
    body_by_file[r['file']] += r['body']
w("| file | methods | body lines |")
w("|---|---:|---:|")
for f, n in sorted(by_file.items(), key=lambda kv: -body_by_file[kv[0]]):
    w(f"| {f} | {n} | {body_by_file[f]} |")
w("")

w("## Longest -- targets for breaking up\n")
w("Everything with a body of 40 lines or more, longest first.\n")
w("| body | total | calls | location | method |")
w("|---:|---:|---:|---|---|")
for r in rows:
    if r['body'] >= 40:
        note = " *(generated data)*" if r['name'] == 'loadConstantData' else ""
        w(f"| {r['body']} | {r['total']} | {r['calls']} | `{r['file']}:{r['line']}` | `{r['name']}`{note} |")
w("")

uncalled = [r for r in rows if r['calls'] == 0]
if uncalled:
    w("## No call sites at all\n")
    w("Residual routines the disassembly had and this port never reaches.\n")
    w("| body | location | method |")
    w("|---:|---|---|")
    for r in sorted(uncalled, key=lambda r: (r['file'], r['line'])):
        w(f"| {r['body']} | `{r['file']}:{r['line']}` | `{r['name']}` |")
    w("")

w("## Shortest -- targets for inlining\n")
w("Methods whose body is a single statement. `calls` is the deciding factor: a")
w("one-statement method with one caller is a pure indirection, while one with")
w("many callers may still be earning its name.\n")
ones = [r for r in rows if r['body'] <= 1]
ones.sort(key=lambda r: (r['calls'], r['file'], r['line']))
w("| calls | body | location | method | statement |")
w("|---:|---:|---|---|---|")
for r in ones:
    m = re.search(r'\{(.*)\}', r['src'], re.S)
    stmt = ' '.join(l.strip() for l in m.group(1).split('\n')
                    if l.strip() and not l.strip().startswith('//')) if m else ''
    stmt = stmt.replace('|', r'\|')
    if r.get('via'): stmt = f"(reached via {r['via']}) " + stmt
    if len(stmt) > 88: stmt = stmt[:85] + '...'
    w(f"| {r['calls']} | {r['body']} | `{r['file']}:{r['line']}` | `{r['name']}` | `{stmt}` |")
w("")

w("## Everything, longest first\n")
w("| body | total | calls | location | method |")
w("|---:|---:|---:|---|---|")
for r in rows:
    w(f"| {r['body']} | {r['total']} | {r['calls']} | `{r['file']}:{r['line']}` | `{r['name']}` |")
w("")
dest = sys.argv[1] if len(sys.argv) > 1 else 'METHOD_LENGTHS.md'
open(dest, 'w').write('\n'.join(out))
print(f'wrote {dest}: {len(rows)} methods')
